---
- name: Install EPEL Repo
  hosts: webservers 
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
    - name: Install EPEL Repo from standard repo
      yum:
        name: epel-release
        state: present
    - name: install First
      yum:
        name: nginx
        state: latest
      tags:
         nginx-package
         packeges
    - name: not copypast
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration
    
  handlers:
    - name: reload nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
